In [1]:
import asrtoolkit

In [2]:
def normalize( txt):
    return txt

def cer(hypothesis, reference):
    hypothesis = normalize(hypothesis)
    reference = normalize(reference)
    return asrtoolkit.cer(reference, hypothesis)

In [3]:
print( cer( 'ax', 'bz'))
print( cer( 'e5', 'c5'))
print( cer( 'e5', 'e5'))
print( cer( 'e5', 'k7'))
print( cer( 'e5', 'f8'))
print( cer( 'e5', 'ff'))
print( cer( 'e5', 'hh'))
print( cer( 'aa', 'zz'))
print( cer( 'e5', 'zz'))



100.0
16.666666666666668
0.0
57.142857142857146
71.42857142857143
250.0
300.0
100.0
300.0


In [11]:
print( asrtoolkit.cer('a4', 'ab'))
print( asrtoolkit.cer('ab', 'a4'))

83.33333333333333
250.0


In [32]:
print( cer( 'a', 'a'))
print( cer( 'a', 'b'))
print( cer( 'a', 'd'))
print( cer( 'e5', 'zz'))
print( cer( 'e5', 'c5'))
print( cer( '0-0', 'e5'))
print( cer( 'e5 d7', 'c5 b7'))
print( cer( 'e5 d7 f8', 'c5 Cb7 f8'))



0.0
100.0
100.0
300.0
16.666666666666668
216.66666666666666
14.285714285714286
13.043478260869565


In [33]:
print( cer( "'d4', 'c5', 'nf3', 'c6', 'd4', '<unk>', 'nd7', 'a6', 'nc3', 'qc7', 'nc3', 'nf6', 'bd3', 'be7', 'nbd2', '<unk>'",
"'e4', 'c5', 'nf3', 'e6', 'd4', 'cd4', 'nd4', 'a6', 'c4', 'qc7', 'nc3', 'nf6', 'be3', 'bb4', 'qd2', 'ne4'"))


21.301775147928993


In [56]:
print( 
cer( 
	"d4 c5 nf3 c6 d4 cd4 nd7 a6 c3 qc7 nc3 nf6 bd3 be7 bd2 ne2",
	"e4 c5 nf3 e6 d4 cd4 nd4 a6 c4 qc7 nc3 nf6 be3 bb4 qd2 ne4"))


19.834710743801654


In [61]:
t1= "d4 c5 nf3 c6 d4 cd4 nd7 a6 c3 qc7 nc3 nf6 bd3 be7 bd2 ne2".split()
t2= "e4 c5 nf3 e6 d4 cd4 nd4 a6 c4 qc7 nc3 nf6 be3 bb4 qd2 ne4".split()
cc= 0
s= []
for i in range( 0, len( t1)):
    s.append( cer( t1[i], t2[i]))

In [62]:
s

[16.666666666666668,
 0.0,
 0.0,
 20.0,
 0.0,
 0.0,
 71.42857142857143,
 0.0,
 83.33333333333333,
 0.0,
 0.0,
 0.0,
 12.5,
 85.71428571428571,
 16.666666666666668,
 57.142857142857146]

In [63]:
cer( ''.join( t1), ''.join( t2))

20.168067226890756

In [64]:
len( ''.join( t1))

42

In [65]:
7/42

0.16666666666666666

In [66]:
8/16

0.5

In [67]:
import jiwer

In [68]:
dir( jiwer)

['AbstractTransform',
 'Compose',
 'ExpandCommonEnglishContractions',
 'RemoveEmptyStrings',
 'RemoveKaldiNonWords',
 'RemoveMultipleSpaces',
 'RemovePunctuation',
 'RemoveSpecificWords',
 'RemoveWhiteSpace',
 'SentencesToListOfWords',
 'Strip',
 'SubstituteRegexes',
 'SubstituteWords',
 'ToLowerCase',
 'ToUpperCase',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'compute_measures',
 'measures',
 'mer',
 'name',
 'transforms',
 'wer',
 'wil',
 'wip']

In [70]:
jiwer.wer( "d4 c5 nf3 c6 d4 cd4 nd7 a6 c3 qc7 nc3 nf6 bd3 be7 bd2 ne2",
	"e4 c5 nf3 e6 d4 cd4 nd4 a6 c4 qc7 nc3 nf6 be3 bb4 qd2 ne4")

0.5

In [71]:
dir( asrtoolkit)

['LOGGER',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 'alignment',
 'audio_file',
 'basename',
 'cer',
 'clean_formatting',
 'clean_up',
 'combine_audio',
 'convert',
 'convert_transcript',
 'corpus',
 'data_structures',
 'deformatting_utils',
 'file_utils',
 'get_distribution',
 'get_extension',
 'logging',
 'sanitize',
 'strip_extension',
 'time_aligned_text',
 'wer']

In [75]:
asrtoolkit.wer( 
"d4 c5 nf3 c6 d4 cd4 nd7 a6 c3 qc7 nc3 nf6 bd3 be7 bd2 ne2",
"e4 c5 nf3 e6 d4 cd4 nd4 a6 c4 qc7 nc3 nf6 be3 bb4 qd2 ne4")

28.125

In [76]:
jiwer.wer( 
"d4 c5 nf3 c6 d4 cd4 nd7 a6 c3 qc7 nc3 nf6 bd3 be7 bd2 ne2",
"e4 c5 nf3 e6 d4 cd4 nd4 a6 c4 qc7 nc3 nf6 be3 bb4 qd2 ne4")

0.5

In [77]:
asrtoolkit.cer( 
"d4 c5 nf3 c6 d4 cd4 nd7 a6 c3 qc7 nc3 nf6 bd3 be7 bd2 ne2",
"e4 c5 nf3 e6 d4 cd4 nd4 a6 c4 qc7 nc3 nf6 be3 bb4 qd2 ne4")

19.51219512195122

In [84]:
jiwer.wer( "hello world", "hello xworld world world")

1.0

In [86]:
ground_truth = ["hello world", "i like monthy python"]
hypothesis = ["hello duck", "i like python"]

print( jiwer.wer(ground_truth, hypothesis))

0.3333333333333333


In [87]:

print( asrtoolkit.wer(ground_truth, hypothesis))

TypeError: expected string or bytes-like object

In [88]:
gt= "I'm André" 
hp= "I'm Andrew"
print( asrtoolkit.wer(gt, hp))
print( jiwer.wer(gt, hp))
print( asrtoolkit.cer(gt, hp))


33.333333333333336
0.5
20.0


In [54]:
import nltk


In [98]:
from nltk import metrics


In [99]:
dir( metrics)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'alignment_error_rate']

In [55]:
from nltk.metrics import distance

In [102]:
print( distance.edit_distance(hp, gt)/len( gt))

0.2222222222222222


In [ ]:
tf.edit_distance(decode, y_true_sparse, normalize=True)

In [12]:
import tensorflow as tf

In [ ]:
tf.edit_distance(decode, y_true_sparse, normalize=True)

In [13]:
class CERMetric(tf.keras.metrics.Metric):
    """
    A custom Keras metric to compute the Character Error Rate
    """
    def __init__(self, name='CER_metric', **kwargs):
        super(CERMetric, self).__init__(name=name, **kwargs)
        self.cer_accumulator = self.add_weight(name="total_cer", initializer="zeros")
        self.counter = self.add_weight(name="cer_count", initializer="zeros")

    def update_state(self, y_true, y_pred, sample_weight=None):
        input_shape = K.shape(y_pred)
        input_length = tf.ones(shape=input_shape[0]) * K.cast(input_shape[1], 'float32')

        decode, log = K.ctc_decode(y_pred,
                                    input_length,
                                    greedy=True)

        decode = K.ctc_label_dense_to_sparse(decode[0], K.cast(input_length, 'int32'))
        y_true_sparse = K.ctc_label_dense_to_sparse(y_true, K.cast(input_length, 'int32'))

        decode = tf.sparse.retain(decode, tf.not_equal(decode.values, -1))
        distance = tf.edit_distance(decode, y_true_sparse, normalize=True)

        self.cer_accumulator.assign_add(tf.reduce_sum(distance))
        self.counter.assign_add(len(y_true))

    def result(self):
        return tf.math.divide_no_nan(self.cer_accumulator, self.counter)

    def reset_states(self):
        self.cer_accumulator.assign(0.0)
        self.counter.assign(0.0)


class WERMetric(tf.keras.metrics.Metric):
    """
    A custom Keras metric to compute the Word Error Rate
    """
    def __init__(self, name='WER_metric', **kwargs):
        super(WERMetric, self).__init__(name=name, **kwargs)
        self.wer_accumulator = self.add_weight(name="total_wer", initializer="zeros")
        self.counter = self.add_weight(name="wer_count", initializer="zeros")

    def update_state(self, y_true, y_pred, sample_weight=None):
        input_shape = K.shape(y_pred)
        input_length = tf.ones(shape=input_shape[0]) * K.cast(input_shape[1], 'float32')

        decode, log = K.ctc_decode(y_pred,
                                    input_length,
                                    greedy=True)

        decode = K.ctc_label_dense_to_sparse(decode[0], K.cast(input_length, 'int32'))
        y_true_sparse = K.ctc_label_dense_to_sparse(y_true, K.cast(input_length, 'int32'))

        decode = tf.sparse.retain(decode, tf.not_equal(decode.values, -1))
        distance = tf.edit_distance(decode, y_true_sparse, normalize=True)
        
        correct_words_amount = tf.reduce_sum(tf.cast(tf.not_equal(distance, 0), tf.float32))

        self.wer_accumulator.assign_add(correct_words_amount)
        self.counter.assign_add(len(y_true))

    def result(self):
        return tf.math.divide_no_nan(self.wer_accumulator, self.counter)

    def reset_states(self):
        self.wer_accumulator.assign(0.0)
        self.counter.assign(0.0)

In [14]:
cer= CERMetric()

In [16]:
cer.update_state( 'ab', 'ac')

NameError: name 'K' is not defined

In [15]:
dir( cer)

['_TF_MODULE_IGNORED_PROPERTIES',
 '__abstractmethods__',
 '__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_activity_regularizer',
 '_add_inbound_node',
 '_add_trackable',
 '_add_variable_with_custom_getter',
 '_attribute_sentinel',
 '_auto_track_sub_layers',
 '_autocast',
 '_build_input_shape',
 '_call_accepts_kwargs',
 '_call_arg_was_passed',
 '_call_fn_args',
 '_call_full_argspec',
 '_callable_losses',
 '_checkpoint_dependencies',
 '_clear_losses',
 '_collect_input_masks',
 '_compute_dtype',
 '_dedup_weights',
 '_deferred_dependencies',
 '_dtype',
 '_dtype_defaulted_to_floatx',
 '_dtype_policy',
 '_dynamic

In [106]:
tf.edit_distance(hp, gt, normalize=True)

TypeError: Hypothesis must be a SparseTensor.

In [ ]:
# https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/edit-distance

In [17]:
# https://github.com/hirofumi0810/tensorflow_end2end_speech_recognition/blob/master/utils/evaluation/edit_distance.py

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np
import tensorflow as tf
import Levenshtein as lev

In [20]:
def compute_edit_distance(labels_true_st, labels_pred_st):
    """Compute edit distance per mini-batch.
    Args:
        session:
        labels_true_st: A `SparseTensor` of ground truth
        labels_pred_st: A `SparseTensor` of prediction
    Returns:
        edit_distances: list of edit distance of each uttearance
    """
    indices, values, dense_shape = labels_true_st
    labels_pred_pl = tf.SparseTensor(indices, values, dense_shape)
    indices, values, dense_shape = labels_pred_st
    labels_true_pl = tf.SparseTensor(indices, values, dense_shape)

    edit_op = tf.edit_distance(labels_pred_pl, labels_true_pl, normalize=True)
    return edit_op
#     edit_distances = session.run(edit_op)
#     return edit_distances

In [21]:
compute_edit_distance( 'ab', 'ac')

ValueError: not enough values to unpack (expected 3, got 2)

In [23]:
tf.string_split( 'abc def')

AttributeError: module 'tensorflow' has no attribute 'string_split'

In [24]:
def string_to_sparse(str_tensor):

    orig_shape = tf.cast(tf.shape(str_tensor), dtype=tf.int64)
    str_tensor = tf.squeeze(str_tensor, axis=0)

    indices = tf.concat([tf.zeros((orig_shape[-1], 1), dtype=tf.int64),
                         tf.expand_dims(tf.range(0, orig_shape[-1]), axis=-1)],
        axis=1)

    return tf.SparseTensor(indices=indices, values=str_tensor,
        dense_shape=orig_shape)

In [31]:
ts= tf.convert_to_tensor("foo", dtype=tf.string)

In [32]:
str_tensor= ts

In [39]:
str_tensor

<tf.Tensor: shape=(), dtype=string, numpy=b'foo'>

In [40]:
tf.shape( [ts, ts])

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([2])>

In [41]:
string_to_sparse([ts, ts])

InvalidArgumentError: Can not squeeze dim[0], expected a dimension of 1, got 2 [Op:Squeeze]

In [38]:
tf.shape(str_tensor)

<tf.Tensor: shape=(0,), dtype=int32, numpy=array([], dtype=int32)>

In [33]:
tf.cast(tf.shape(str_tensor), dtype=tf.int64)

<tf.Tensor: shape=(0,), dtype=int64, numpy=array([], dtype=int64)>

In [36]:
orig_shape = tf.cast(tf.shape(str_tensor), dtype=tf.int64)

In [37]:
tf.concat([tf.zeros((orig_shape[-1], 1), dtype=tf.int64),
                         tf.expand_dims(tf.range(0, orig_shape[-1]), axis=-1)],
        axis=1)

InvalidArgumentError: slice index -1 of dimension 0 out of bounds. [Op:StridedSlice] name: strided_slice/

In [42]:
def levenshtein(s1,s2): 
   
    if len(s1) > len(s2):
        s1,s2 = s2,s1 
    distances = range(len(s1) + 1) 

    for index2,char2 in enumerate(s2):
        newDistances = [index2+1]
        for index1,char1 in enumerate(s1):
            if char1 == char2:
                newDistances.append(distances[index1]) 
            else:
                newDistances.append(1 + min((distances[index1], distances[index1+1], newDistances[-1]))) 
                distances = newDistances 

                return distances[-1]

print(levenshtein("analyze","analyse"))

1


In [43]:
print(levenshtein("ab","ac"))

1


In [51]:
print(levenshtein("x","z"))

1


In [58]:
def _cir( hp, gt):
    return distance.edit_distance(hp, gt)/len( gt)

In [62]:
print( _cir( "Bd4", "Bxd4"))
print( _cir( "Bxd4", "Bd4"))
print( _cir( "c4", "e4"))
print( _cir( "d5", "e5"))


0.25
0.3333333333333333
0.5
0.5


In [67]:
tf.math.reduce_mean( [1, 2, 3]).numpy()

2

In [69]:
import statistics

In [70]:
print( statistics.mean([1,2,3]))

2


In [71]:
predicted= ['Nc3', 'd5', 'd4', 'd4', 'Nxe4', 'e5', 'Nc3', 'Nf6', 'd4', 'Nd6', 'Nf3', 'Be6', 'd3', 'b6', 'a4', 'b6']
expected= ['Nc3', 'd5', 'e4', 'd4', 'Nce2', 'e5', 'Ng3', 'Nf6', 'Bc4', 'Nc6', 'Nf3', 'Bd6', 'd3', 'h6', 'a3', 'Qe7']

In [75]:
predicted= [p.replace("\'", "") for p in predicted]
expected= [p.replace("\'", "") for p in expected]

In [76]:
predicted, expected

(['Nc3',
  'd5',
  'd4',
  'd4',
  'Nxe4',
  'e5',
  'Nc3',
  'Nf6',
  'd4',
  'Nd6',
  'Nf3',
  'Be6',
  'd3',
  'b6',
  'a4',
  'b6'],
 ['Nc3',
  'd5',
  'e4',
  'd4',
  'Nce2',
  'e5',
  'Ng3',
  'Nf6',
  'Bc4',
  'Nc6',
  'Nf3',
  'Bd6',
  'd3',
  'h6',
  'a3',
  'Qe7'])

In [78]:
print( len( predicted), len( expected))

16 16


In [86]:
tf.reduce_mean( [_cir(e, p) for (e, p) in zip( expected, predicted)]).numpy()

0.55

In [92]:
def __cir( acc, expected, predicted):
    print( 'acc', acc, 'cir', tf.reduce_mean( [_cir(e, p) for (e, p) in zip( expected, predicted)]).numpy())

In [89]:
predicted= ['c4', 'e5', 'Nf3', 'e6', 'Bc4', 'dxe4', 'Nxe4', 'Nxc6', 'O-O', 'd6', 'Nxc6', 'c5', 'N5c3', 'Bg4', 'Bd3']
expected= ['e4', 'c5', 'Nf3', 'd6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'a6', 'Be2', 'e5', 'Nb3', 'Be7', 'Bg5', 'Be6']
__cir( 0.066, expected, predicted)

acc 0.006 cir 0.55


In [93]:
predicted= ['d4', 'e6', 'c4', 'c5', 'Nf3', 'Nf6', 'Bg2', 'h6', 'Bh4', 'Qb6', 'b3', 'Nc6', 'e3', 'd5', 'Bg5']
expected= ['d4', 'e6', 'c4', 'c5', 'Nf3', 'Nf6', 'Bg5', 'h6', 'Bh4', 'Qb6', 'b3', 'Nc6', 'e3', 'g5', 'Bg3']
__cir( 0.8, expected, predicted)

acc 0.8 cir 0.07777778


In [ ]:
# TODO: Implementar CIR em Accucary-of--

In [100]:
def cir_word( hp, gt):
    return distance.edit_distance(hp, gt)/len( gt)
	
def cir_line( expected, predicted):
    return tf.reduce_mean( [cir_word(e, p) for (e, p) in zip( expected, predicted)]).numpy()

def cir_set( labels, result, _len):
    return tf.reduce_mean( [cir_line(e[:_len], p[:_len]) for (e, p) in zip( labels, result)]).numpy()

print( cir_word( 'd4', 'c4'))
print( cir_line( ['d4', 'c6', 'e4'], ['d4', 'e6', 'c4']))
print( cir_set( [['d4', 'c6', 'e4']], [['d4', 'e6', 'c4']], 1))


0.5
0.33333334
0.0


In [95]:
[1,2,3][0:3]

[1, 2, 3]

In [101]:
for i in range( 2):
    print( i)

0
1
