In [1]:
import math

#find the exponential of the specified value
print(math.exp(65))
print(math.exp(-6.89))

1.6948892444103338e+28
0.0010179138409954387


In [5]:
def logit2prob(logit):
    odds = math.exp(logit)
    prob = odds / (1 + odds)
    return prob


In [7]:
print( logit2prob(1))
print( logit2prob(5))
print( logit2prob(3))

0.7310585786300049
0.9933071490757152
0.9525741268224333


In [8]:
import numpy as np

# # your solution:
# def your_softmax(x):
#     """Compute softmax values for each sets of scores in x."""
#     e_x = np.exp(x - np.max(x))
#     return e_x / e_x.sum()

# correct solution:
def softmax(x):
    """Compute softmax values for each sets of scores in x."""
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0) # only difference

In [13]:
def pre_softmax(x):
    """Compute softmax values for each sets of scores in x."""
    e_x = np.exp(x - np.max(x))
    return e_x

In [10]:
scores = [1.0, 5.0, 3.0]
print(softmax(scores))

[0.01587624 0.86681333 0.11731043]


In [14]:
scores = [1.0, 5.0, 3.0]
print(pre_softmax(scores))

[0.01831564 1.         0.13533528]


In [15]:
def sigmoid( x):
    return np.exp( x)/ (1+ np.exp( x))

In [16]:
sigmoid(  [1.0, 5.0, 3.0])

array([0.73105858, 0.99330715, 0.95257413])

In [20]:
nn= scores - np.max(scores)
nn

array([-4.,  0., -2.])

In [22]:
ne= np.exp( nn)
ne

array([0.01831564, 1.        , 0.13533528])

In [23]:
ne/ ne.sum(axis=0)

array([0.01587624, 0.86681333, 0.11731043])

In [25]:
import tensorflow as tf

In [34]:
tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)(y_true=1, y_pred=[1.0, 5.0, 3.0]).numpy()

0.1429317

In [31]:
tf.keras.losses.SparseCategoricalCrossentropy(2, [1.0, 5.0, 3.0])

ValueError: Invalid Reduction Key [1.0, 5.0, 3.0].